sprint_10 is done
DmnUAll/ImageFeed-ios pull request #3
Opened 2022-12-16 11:11 UTC by DmnUAll

Splash screen added
Authentication and authorisation logics added

2022-12-17 10:07 UTC, ABashkirova requested changes

2022-12-17 10:07 UTC, ABashkirova commented on ImageFeed/Auth/AuthViewController.swift
> +        let nextVC = storyBoard.instantiateViewController(withIdentifier: "MainFlow") as! UITabBarController
Не рекоумендую использовать любые force-операции в тестовых проектах, и работах для портфолио. Это небезопсные операции, и к ним очень пристальное внимание у работадателей. Лучше всего – всегда попробовать разыменовать  или мягко скастить в if или guard (as?)

2022-12-17 10:07 UTC, ABashkirova commented on ImageFeed/Auth/WebViewViewController.swift
> +}
control+i - чтобы поправить форматриование

2022-12-17 10:07 UTC, ABashkirova commented on ImageFeed/SplashScreen/SplashViewController.swift
> +        sleep(1)
слипы стоит удалить

2022-12-17 11:42 UTC, DmnUAll commented on ImageFeed/Auth/AuthViewController.swift
> +        let nextVC = storyBoard.instantiateViewController(withIdentifier: "MainFlow") as! UITabBarController
Fixed :)

2022-12-17 11:42 UTC, DmnUAll commented on ImageFeed/Auth/WebViewViewController.swift
> +}
Fixed :)

2022-12-17 11:42 UTC, DmnUAll commented on ImageFeed/SplashScreen/SplashViewController.swift
> +        sleep(1)
Fixed :)

2022-12-17 15:31 UTC, DmnUAll commented
Will re-open the pull-request, applying fixes, based on code-reviewer comments

2022-12-17 15:31 UTC, closed without merging

2022-12-18 10:21 UTC, ABashkirova commented
Why did you open PR again? Work on one sprint should be done in one pull request

2022-12-18 12:59 UTC, DmnUAll commented
My bad! 
I thought that I should re-create the pull request again after fixing the errors in the code.
On the platform (YP), when resubmitting homework, it says - send a new link.
I'll keep that in mind for the future.