Sprint 12
DmnUAll/ImageFeed-ios pull request #6
Opened 2023-01-21 19:33 UTC by DmnUAll

Sprint 12 was done.
Whole UI is now implemented by code (storyboard realisation was excluded).

2023-01-22 13:39 UTC, IBDesignable requested changes

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +}
Верстка кодом ОК, но будь внимателен, на некоторых экранах цвет бекграунда перестал соответствовать макетам

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/Helpers/Date+Extensions.swift
> +        let dateFormatter = ISO8601DateFormatter()
Этот метод вызывается для каждого фото, это не хорjшо, так как создание под капотом может занимать много ресурсов. Рекомендую использовать похожий подход, что и в MovieQuiz, там использовалась статика, или как предлагают авторы, создать один форматтер в классе, где он тебе нужен. 

> Обратите внимание: объект форматтер желательно создать один раз (например, в конструкторе класса, который его использует), а затем переиспользовать. При создании форматтера может «под капотом» выделяться много дополнительной памяти, необходимой для хранения всех внутренних структур этого класса, что при частом выполнении (например, если для каждой отдельной фотографии мы создаём новый форматтер) может приводить к замедлению производительности. Этот комментарий относится ко всем форматтерам, которые будут использованы в проекте.

Подробнее:
https://sarunw.com/posts/how-expensive-is-dateformatter/

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/ImageList/ImagesListCell.swift
> +        label.tintColor = .ypWhite
textColor, иначе в темном режиме лейбла будет черной

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/ImageList/ImagesListViewController.swift
>          }
Здесь уместнее использовать if let

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/ImageList/ImagesListViewController.swift
> +        if oldCount != newCount {
а здесь наоборот, уместнее использовать guard

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/ImageList/ImagesListViewController.swift
> +        return cell
если нет необходимости в промежуточной переменной, можно сразу возвращать вызов метода

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/ImageList/ImagesListViewController.swift
> +//                    } completion: { _ in }
давай не оставлять закомменченный код

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/ImageList/ImagesListViewController.swift
> +                    UIBlockingProgressHUD.dismiss()
можно `UIBlockingProgressHUD.dismiss()` вызвать один раз, если вынести его за swich, здесь уместнее после него

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/Model/Photo.swift
> +    var thumbImageCastedURL: URL {
Я в работе обычно разделяю вычислимые свойства от обычных одной пустой строкой, потому что иначе для меня выглядит слишком слипшимся куском. 

Дополнительный материал про кодстайл:  

- [Подробное описание codestyle](https://google.github.io/swift/) от Google
- [От Ray Wanderlich](https://github.com/raywenderlich/swift-style-guide)
- [На русском от команды tutu](https://github.com/tutu-ru/swift-style-guide)

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +            KeychainWrapper.standard.removeObject(forKey: "bearerToken")
я здесь не ожидаю использование внешних фреймворков, для этого у нас уже есть датаCторадж, и можем тогда опционад в токен передать, там же на опшинал как раз можно вызывать эту функцию, тогда код будет выглядеть проще:

tokenStorage.token = nil

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +                                               isLiked: item.likedByUser)
можно сделать для PhotosResult здесь приватный экстеншен, и написать в нем функцию convertToViewModel(), тогда код чуть упростится. 

Из вместо цикла, можно будет использовать функциональщину:

let photos = data.map { $0.convertToViewModel() } 

и одной строчкой добавить весь новый комплект:

self.photos.append(elements: photos) // не помню синтаксис, там две для коллекции и для одного элемента

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +                let data = try result.get()
Я не очень понимаю, зачем опшионал доставать через try, когда есть понятные if let / guard let

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +                NotificationCenter.default.post(name: ImagesListService.DidChangeNotification,
по заданию, фото надо добавить с главной очереди, и нотификацию я бы тоже с нее послала.

2023-01-22 13:39 UTC, IBDesignable commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +                    UIBlockingProgressHUD.dismiss()
здесь тоже задисмисить можно один раз

2023-01-22 14:07 UTC, DmnUAll commented on ImageFeed/Auth/AuthViewController.swift
> +}
Пофиксил :)

2023-01-22 14:47 UTC, DmnUAll commented on ImageFeed/Helpers/Date+Extensions.swift
> +        let dateFormatter = ISO8601DateFormatter()
Пофиксил :)

2023-01-22 14:49 UTC, DmnUAll commented on ImageFeed/ImageList/ImagesListCell.swift
> +        label.tintColor = .ypWhite
Fixed :)

2023-01-22 14:53 UTC, DmnUAll commented on ImageFeed/ImageList/ImagesListViewController.swift
>          }
Fixed

2023-01-22 14:58 UTC, DmnUAll commented on ImageFeed/ImageList/ImagesListViewController.swift
> +        if oldCount != newCount {
Fixed

2023-01-22 15:14 UTC, DmnUAll commented on ImageFeed/ImageList/ImagesListViewController.swift
> +//                    } completion: { _ in }
Убрал лишние комментарии из кода

2023-01-22 15:16 UTC, DmnUAll commented on ImageFeed/ImageList/ImagesListViewController.swift
> +        return cell
Убрал не используемую, промежуточную, переменную

2023-01-22 15:18 UTC, DmnUAll commented on ImageFeed/ImageList/ImagesListViewController.swift
> +                    UIBlockingProgressHUD.dismiss()
Вынес метод разблокировки UI за пределы switch

2023-01-22 15:19 UTC, DmnUAll commented on ImageFeed/Model/Photo.swift
> +    var thumbImageCastedURL: URL {
Добавил промежутки, в соответствии с Code-style

2023-01-22 15:34 UTC, DmnUAll commented on ImageFeed/Profile/ProfileViewController.swift
> +            KeychainWrapper.standard.removeObject(forKey: "bearerToken")
Переработал логику yesAction

2023-01-22 15:53 UTC, DmnUAll commented on ImageFeed/Services/ImagesListService.swift
> +                                               isLiked: item.likedByUser)
Оптимизировал код, согласно рекомендации

2023-01-22 16:08 UTC, DmnUAll commented on ImageFeed/Services/ImagesListService.swift
> +                let data = try result.get()
Не уверен, что правильно, но - переделал :)

2023-01-22 16:14 UTC, DmnUAll commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +                    UIBlockingProgressHUD.dismiss()
Done

2023-01-22 17:22 UTC, DmnUAll commented on ImageFeed/Services/ImagesListService.swift
> +                NotificationCenter.default.post(name: ImagesListService.DidChangeNotification,
Исправил :)

2023-01-23 18:35 UTC, IBDesignable approved these changes

2023-01-23 18:35 UTC, IBDesignable commented on ImageFeed/Helpers/DateFormatter+Extensions.swift
> +        return formatter
Здесь не понадобиалась настройка, поэтому можно обойтись без замыкания и сделать в одну строчку

2023-01-23 18:35 UTC, IBDesignable commented on ImageFeed/Model/PhotoLikeResult.swift
> +}
приватный же экстеншен, он тут нигде в файле не используется, во вне тоже не будет доступен

2023-01-23 18:35 UTC, IBDesignable commented on ImageFeed/Model/PhotoLikeResult.swift
> +}
Можно здесь удалить, оставить такой только там где используешь

2023-01-23 18:35 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
>                  }
```swift
guard let self else {
  completion(.failure(NetworkError.dataError))
  return 
}

switch result {
case .success(let photo): 
   /// здесь вставляешь по индексу, аналогично твоему коду
   completion(.success())
case .failure(let error):
   completion(.failure)
}
self.task = nil
```

у result.get вызывать нет причины

2023-01-23 18:35 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +                     isLiked: self.photo.likedByUser)
self можно опустить

2023-01-23 18:35 UTC, IBDesignable commented on ImageFeed/Services/OAuth2TokenStorage.swift
>              saveToKeyChain(value: newValue)
Хорошо бы в отдельную переменную KeychainWrapper.standard, и вот такой подход использовать. а то у тебя в обе строчки заход при nil выполнятся
```
if let token = newValue {
  saveToKeychain()
} 
else {
  keychain.removeObject()
}

```

2023-01-24 07:07 UTC, DmnUAll commented on ImageFeed/Helpers/DateFormatter+Extensions.swift
> +        return formatter
Done

2023-01-24 07:10 UTC, DmnUAll commented on ImageFeed/Model/PhotoLikeResult.swift
> +}
Забыл удалить это расширение, после того, как добавил его в ImagesListService... 
Готово :)

2023-01-24 07:30 UTC, DmnUAll commented on ImageFeed/Services/ImagesListService.swift
>                  }
Done

2023-01-24 07:31 UTC, DmnUAll commented on ImageFeed/Services/ImagesListService.swift
> +                     isLiked: self.photo.likedByUser)
Done

2023-01-24 07:37 UTC, DmnUAll commented on ImageFeed/Services/OAuth2TokenStorage.swift
>              saveToKeyChain(value: newValue)
Done

2023-01-24 07:39 UTC, merged